# Generated by Django 5.1.9 on 2025-06-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentik_core", "0048_delete_oldauthenticatedsession_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWeComSourceConnection",
            fields=[
                (
                    "usersourceconnection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_core.usersourceconnection",
                    ),
                ),
                ("access_token", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "verbose_name": "User WeCom Source Connection",
                "verbose_name_plural": "User WeCom Source Connections",
            },
            bases=("authentik_core.usersourceconnection",),
        ),
        migrations.CreateModel(
            name="WeComSource",
            fields=[
                (
                    "source_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_core.source",
                    ),
                ),
                ("corp_id", models.TextField(help_text="Corp identifier used to talk to WeCom.")),
                ("agent_id", models.TextField(help_text="Agent identifier used to talk to WeCom.")),
                ("secret", models.TextField(help_text="Secret used to talk to WeCom.")),
            ],
            options={
                "verbose_name": "WeCom Source",
                "verbose_name_plural": "WeCom Sources",
            },
            bases=("authentik_core.source",),
        ),
        migrations.CreateModel(
            name="WeComSourcePropertyMapping",
            fields=[
                (
                    "propertymapping_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authentik_core.propertymapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "WeCom Source Property Mapping",
                "verbose_name_plural": "WeCom Source Property Mappings",
            },
            bases=("authentik_core.propertymapping",),
        ),
    ]
