# Generated by Django 5.1.9 on 2025-06-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentik_sources_wecom", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userwecomsourceconnection",
            name="access_token",
        ),
    ]
