---
name: authentik-on-release

on:
  release:
    types: [published, created]

jobs:
  build-server:
    uses: ./.github/workflows/_reusable-docker-build.yaml
    secrets: inherit
    permissions:
      # Needed to upload container images to ghcr.io
      packages: write
      # Needed for attestation
      id-token: write
      attestations: write
    with:
      image_name: ghcr.io/ezcoding-dev-team/authentik/server
      release: true
      registry_ghcr: true
